# Horizon Reports End User Documentation Config
# To customize the help, edit the settings in the Documentation Settings section:

#Horizon Reports Documentation Settings
title: Horizon Reports
email: support@horizon-reports.com
app_name: Horizon Reports
has_datagroups: true
has_multilanguage: true
has_multidatasource: true
has_tenants: true
manage_conn_string: true
query_values: true
users_can_register: true
allow_password_reset: true
manage_dsn: false
support_center: true
support_kb: false
demo_days: 30
company: TNM Software
description: Documentation for Horizon Reports ad hoc reporting software
url: "https://docs.horizon-reports.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/banner.png"


# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
 
# Settings for just-the-docs
color_scheme: dark
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
  
callouts:
  note:
    title: Note
    color: orange
  tip:
    title: Tip
    color: white
  
# Aux links for the upper right navigation
#aux_links:
#  "Just the Docs on GitHub":
#    - "//github.com/pmarsceill/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-5555555-55
#ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

github_username:  tmansuy

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true
    
just_the_docs:
  collections:
    docs:
      name: Horizon Reports Documentation
